Update 5.internal-document-search-deploy.yml

diff --git a/.github/workflows/5.internal-document-search-deploy.yml b/.github/workflows/5.internal-document-search-deploy.yml
--- a/.github/workflows/5.internal-document-search-deploy.yml
+++ b/.github/workflows/5.internal-document-search-deploy.yml
@@ -55,17 +55,21 @@ jobs:
 
             cd 5.internal-document-search/infra
             $results = az deployment sub create --name $ENV:DEP_NAME --location $ENV:LOC --template-file main.bicep --parameters principalId=$ENV:AZURE_PRINCIPAL_ID environmentName=$ENV:AZURE_ENV_NAME location=$ENV:LOC backendServiceName=$ENV:BACKEND_SERVICE_NAME appServicePlanName=$ENV:APP_SERVICE_PLAN_NAME storageAccountName=$ENV:STORAGE_ACCOUNT_NAME searchServiceName=$ENV:SEARCH_SERVICE_NAME formRecognizerServiceName=$ENV:FORMRECOGNIZER_SERVICE_NAME openAiServiceName=$ENV:COGNITIVE_SERVICES_NAME vmLoginPassword=dummy isPrivateNetworkEnabled=false
-            
+
+            echo "`$results`:"
             echo "$results"
 
-            if ($results.Contains("ERROR")) {
-              echo "Deployment failed"
-              exit 1
-            }
-            if ($results.Contains("InsufficientQuota")) {
-              echo "Fix AOAI quota!"
-              exit 1
-            }
+            if ($null -ne $results) {
+              if ($results.Contains("ERROR")) {
+                echo "Deployment failed"
+                exit 1
+              }
+              if ($results.Contains("InsufficientQuota")) {
+                echo "Fix AOAI quota!"
+                exit 1
+              }
+            } else {
+              echo "`$results` is null"
           azPSVersion: "latest"
 
       - name: Build frontend
